<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://www.antel.com.uy/servicio/epagos/suscripciones-v6.0"
                  xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                  name="ConsultaSuscripcionesServiceFinalService" targetNamespace="http://www.antel.com.uy/servicio/epagos/suscripciones-v6.0">
  <wsdl:types>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.antel.com.uy/servicio/epagos/suscripciones-v6.0" elementFormDefault="qualified" targetNamespace="http://www.antel.com.uy/servicio/epagos/suscripciones-v6.0" version="1.0">

  <xs:element name="consultaUsuarioSuscripcionesDTO" type="tns:consultaUsuarioSuscripcionesDTO"/>

  <xs:element name="consultarUsuarioSuscripciones" type="tns:consultarUsuarioSuscripciones"/>

  <xs:complexType name="consultarUsuarioSuscripciones">
    <xs:sequence>
      <xs:element minOccurs="0" ref="tns:consultaUsuarioSuscripcionesDTO"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="consultaUsuarioSuscripcionesDTO">
    <xs:sequence>
      <xs:element name="id-cliente" type="xs:string"/>
      <xs:element name="codigo-comercio" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>
  </wsdl:types>
  <wsdl:message name="consultarUsuarioSuscripciones">
    <wsdl:part element="tns:consultarUsuarioSuscripciones" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="Request">
    <wsdl:operation name="consultarUsuarioSuscripciones">
      <wsdl:input message="tns:consultarUsuarioSuscripciones" name="consultarUsuarioSuscripciones">
    </wsdl:input>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="ConsultaSuscripcionesServiceFinalServiceSoapBinding" type="tns:Request">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="consultarUsuarioSuscripciones">
      <soap12:operation soapAction="urn:antel:mdm:system:epagos:b2b:comercio:consultaSuscripciones" style="document"/>
      <wsdl:input name="consultarUsuarioSuscripciones">
        <soap12:body use="literal"/>
      </wsdl:input>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ConsultaSuscripcionesServiceFinalService">
    <wsdl:port binding="tns:ConsultaSuscripcionesServiceFinalServiceSoapBinding" name="ConsultaSuscripcionesPort">
      <soap12:address location="https://antel.com.uy/endpoint/"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>